Global:
  use_pretrain: True
  num_epoch: 10
  warmup_epoch: 0
  checkpoints: /content/drive/MyDrive/FACE_Project/CHECKPOINT_REG


Architecture:
  Backbone:
    name: IResnet
    layers: [3, 4, 14, 3]
  Head:
    name: PartialFC_V2
    embedding_size: 512
    num_classes: 85742
    sample_rate: 1.0


Loss:
  margin_list: [1.0, 0.5, 0.0]
  interclass_filtering_threshold: 0


Save:
  save_iter: 3000


Optimizer:
  gradient_acc: 1.0
  lr: 0.1
  weight_decay: 0.0005
  last_epoch: -1

Dataloader:
  name: loader
  num_image: 5822653
  batch_size: 64
  root_dir: /content/Face_reg/DATASET/faces_emore/


